### ISSUE TITLE
[Feature request] Avatar command

### ISSUE THREAD

**Issue by Arzte** [gearbot/GearBot#227]
Basically im wanting it so that you can get someone's avatar without having to use the profile command which gives a huge (helpful) embed, which for the one aspect is a little much.

**Comment by Tarek1337** [comment]
Use case? I can pr something for it. I'm just curious what the use case is besides from encouraging avatar stealing

**Comment by Arzte** [comment]
Mostly to see if an unclear avatar is actually nsfw or similarly something undesirable for a server.

**Comment by trilleplay** [comment]
Dont see why this would be needed, it just feels like its cluttering the command list, I mean is it really that hard to use the userinfo command and click on the avatar for a larger picture? Just my opinion.

**Comment by AEnterprise** [comment]
i currently don't see a use for adding an separate command for it since userinfo can do this and it might enourage stealing other people's avatars

as for the problem of the embed beinghuge: i might add some options later to decide what is shown but for now if it is taking up too much space you can just delete it after you are done with it
